version: '3.3'

services:
  app:
    build: .
    container_name: northwind-app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db/mydb
    ports:
      - '3000:3000'
    restart: on-failure:3

  db:
    container_name: northwind-db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    image: postgres:18
    ports: ['127.0.0.1:5432:5432'] # dev
    restart: on-failure:3
    volumes:
      - pg_volume:/var/lib/postgresql

volumes:
  pg_volume:
