version: '3.3'

services:
  app:
    container_name: northwind-app
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db/mydb

  db:
    container_name: northwind-db
    image: postgres:18
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - ./docker/db:/var/lib/postgresql
    ports: ['5432:5432']
